### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-test-helpers#2]
Follow these [steps](https://canjs.com/doc/guides/contributing/adding-ecosystem-modules.html) to add this package to the canjs tests/docs.

**Comment by justinbmeyer** [comment]
I don't think we need to document this.  Just distracting for people using CanJS.

**Comment by phillipskevin** [comment]
How do people contributing to canjs know how to use it? Move the docs to the readme? Add a new page in the contributing guide?

**Comment by Macrofig** [comment]
Todos, per discussion from  standup:

- [ ] Add link to contributing guide
- [ ] Document in repo's readme
